# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aleksey/MSTU/OOP/lab3/Frame_Viewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aleksey/MSTU/OOP/lab3/Frame_Viewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aleksey/MSTU/OOP/lab3/Frame_Viewer/CMakeFiles /home/aleksey/MSTU/OOP/lab3/Frame_Viewer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aleksey/MSTU/OOP/lab3/Frame_Viewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OOP_Lab3_FrameViewer

# Build rule for target.
OOP_Lab3_FrameViewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OOP_Lab3_FrameViewer
.PHONY : OOP_Lab3_FrameViewer

# fast build rule for target.
OOP_Lab3_FrameViewer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/build
.PHONY : OOP_Lab3_FrameViewer/fast

#=============================================================================
# Target rules for targets named OOP_Lab3_FrameViewer_autogen_timestamp_deps

# Build rule for target.
OOP_Lab3_FrameViewer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OOP_Lab3_FrameViewer_autogen_timestamp_deps
.PHONY : OOP_Lab3_FrameViewer_autogen_timestamp_deps

# fast build rule for target.
OOP_Lab3_FrameViewer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer_autogen_timestamp_deps.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer_autogen_timestamp_deps.dir/build
.PHONY : OOP_Lab3_FrameViewer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named OOP_Lab3_FrameViewer_autogen

# Build rule for target.
OOP_Lab3_FrameViewer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OOP_Lab3_FrameViewer_autogen
.PHONY : OOP_Lab3_FrameViewer_autogen

# fast build rule for target.
OOP_Lab3_FrameViewer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer_autogen.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer_autogen.dir/build
.PHONY : OOP_Lab3_FrameViewer_autogen/fast

OOP_Lab3_FrameViewer_autogen/mocs_compilation.o: OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.o
.PHONY : OOP_Lab3_FrameViewer_autogen/mocs_compilation.o

# target to build an object file
OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.o
.PHONY : OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.o

OOP_Lab3_FrameViewer_autogen/mocs_compilation.i: OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.i
.PHONY : OOP_Lab3_FrameViewer_autogen/mocs_compilation.i

# target to preprocess a source file
OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.i
.PHONY : OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.i

OOP_Lab3_FrameViewer_autogen/mocs_compilation.s: OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.s
.PHONY : OOP_Lab3_FrameViewer_autogen/mocs_compilation.s

# target to generate assembly for a file
OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.s
.PHONY : OOP_Lab3_FrameViewer_autogen/mocs_compilation.cpp.s

src/bridge/AssimpModelImpl.o: src/bridge/AssimpModelImpl.cpp.o
.PHONY : src/bridge/AssimpModelImpl.o

# target to build an object file
src/bridge/AssimpModelImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/AssimpModelImpl.cpp.o
.PHONY : src/bridge/AssimpModelImpl.cpp.o

src/bridge/AssimpModelImpl.i: src/bridge/AssimpModelImpl.cpp.i
.PHONY : src/bridge/AssimpModelImpl.i

# target to preprocess a source file
src/bridge/AssimpModelImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/AssimpModelImpl.cpp.i
.PHONY : src/bridge/AssimpModelImpl.cpp.i

src/bridge/AssimpModelImpl.s: src/bridge/AssimpModelImpl.cpp.s
.PHONY : src/bridge/AssimpModelImpl.s

# target to generate assembly for a file
src/bridge/AssimpModelImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/AssimpModelImpl.cpp.s
.PHONY : src/bridge/AssimpModelImpl.cpp.s

src/bridge/CarcasCamera.o: src/bridge/CarcasCamera.cpp.o
.PHONY : src/bridge/CarcasCamera.o

# target to build an object file
src/bridge/CarcasCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/CarcasCamera.cpp.o
.PHONY : src/bridge/CarcasCamera.cpp.o

src/bridge/CarcasCamera.i: src/bridge/CarcasCamera.cpp.i
.PHONY : src/bridge/CarcasCamera.i

# target to preprocess a source file
src/bridge/CarcasCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/CarcasCamera.cpp.i
.PHONY : src/bridge/CarcasCamera.cpp.i

src/bridge/CarcasCamera.s: src/bridge/CarcasCamera.cpp.s
.PHONY : src/bridge/CarcasCamera.s

# target to generate assembly for a file
src/bridge/CarcasCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/CarcasCamera.cpp.s
.PHONY : src/bridge/CarcasCamera.cpp.s

src/bridge/LightImpl.o: src/bridge/LightImpl.cpp.o
.PHONY : src/bridge/LightImpl.o

# target to build an object file
src/bridge/LightImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/LightImpl.cpp.o
.PHONY : src/bridge/LightImpl.cpp.o

src/bridge/LightImpl.i: src/bridge/LightImpl.cpp.i
.PHONY : src/bridge/LightImpl.i

# target to preprocess a source file
src/bridge/LightImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/LightImpl.cpp.i
.PHONY : src/bridge/LightImpl.cpp.i

src/bridge/LightImpl.s: src/bridge/LightImpl.cpp.s
.PHONY : src/bridge/LightImpl.s

# target to generate assembly for a file
src/bridge/LightImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/LightImpl.cpp.s
.PHONY : src/bridge/LightImpl.cpp.s

src/bridge/VectorCompositeImpl.o: src/bridge/VectorCompositeImpl.cpp.o
.PHONY : src/bridge/VectorCompositeImpl.o

# target to build an object file
src/bridge/VectorCompositeImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/VectorCompositeImpl.cpp.o
.PHONY : src/bridge/VectorCompositeImpl.cpp.o

src/bridge/VectorCompositeImpl.i: src/bridge/VectorCompositeImpl.cpp.i
.PHONY : src/bridge/VectorCompositeImpl.i

# target to preprocess a source file
src/bridge/VectorCompositeImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/VectorCompositeImpl.cpp.i
.PHONY : src/bridge/VectorCompositeImpl.cpp.i

src/bridge/VectorCompositeImpl.s: src/bridge/VectorCompositeImpl.cpp.s
.PHONY : src/bridge/VectorCompositeImpl.s

# target to generate assembly for a file
src/bridge/VectorCompositeImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/bridge/VectorCompositeImpl.cpp.s
.PHONY : src/bridge/VectorCompositeImpl.cpp.s

src/builder/AssimpModelBuilder.o: src/builder/AssimpModelBuilder.cpp.o
.PHONY : src/builder/AssimpModelBuilder.o

# target to build an object file
src/builder/AssimpModelBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/AssimpModelBuilder.cpp.o
.PHONY : src/builder/AssimpModelBuilder.cpp.o

src/builder/AssimpModelBuilder.i: src/builder/AssimpModelBuilder.cpp.i
.PHONY : src/builder/AssimpModelBuilder.i

# target to preprocess a source file
src/builder/AssimpModelBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/AssimpModelBuilder.cpp.i
.PHONY : src/builder/AssimpModelBuilder.cpp.i

src/builder/AssimpModelBuilder.s: src/builder/AssimpModelBuilder.cpp.s
.PHONY : src/builder/AssimpModelBuilder.s

# target to generate assembly for a file
src/builder/AssimpModelBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/AssimpModelBuilder.cpp.s
.PHONY : src/builder/AssimpModelBuilder.cpp.s

src/builder/BaseBuilder.o: src/builder/BaseBuilder.cpp.o
.PHONY : src/builder/BaseBuilder.o

# target to build an object file
src/builder/BaseBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/BaseBuilder.cpp.o
.PHONY : src/builder/BaseBuilder.cpp.o

src/builder/BaseBuilder.i: src/builder/BaseBuilder.cpp.i
.PHONY : src/builder/BaseBuilder.i

# target to preprocess a source file
src/builder/BaseBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/BaseBuilder.cpp.i
.PHONY : src/builder/BaseBuilder.cpp.i

src/builder/BaseBuilder.s: src/builder/BaseBuilder.cpp.s
.PHONY : src/builder/BaseBuilder.s

# target to generate assembly for a file
src/builder/BaseBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/BaseBuilder.cpp.s
.PHONY : src/builder/BaseBuilder.cpp.s

src/builder/CarcasCameraBuilder.o: src/builder/CarcasCameraBuilder.cpp.o
.PHONY : src/builder/CarcasCameraBuilder.o

# target to build an object file
src/builder/CarcasCameraBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/CarcasCameraBuilder.cpp.o
.PHONY : src/builder/CarcasCameraBuilder.cpp.o

src/builder/CarcasCameraBuilder.i: src/builder/CarcasCameraBuilder.cpp.i
.PHONY : src/builder/CarcasCameraBuilder.i

# target to preprocess a source file
src/builder/CarcasCameraBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/CarcasCameraBuilder.cpp.i
.PHONY : src/builder/CarcasCameraBuilder.cpp.i

src/builder/CarcasCameraBuilder.s: src/builder/CarcasCameraBuilder.cpp.s
.PHONY : src/builder/CarcasCameraBuilder.s

# target to generate assembly for a file
src/builder/CarcasCameraBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/CarcasCameraBuilder.cpp.s
.PHONY : src/builder/CarcasCameraBuilder.cpp.s

src/builder/CarcasModelBuilder.o: src/builder/CarcasModelBuilder.cpp.o
.PHONY : src/builder/CarcasModelBuilder.o

# target to build an object file
src/builder/CarcasModelBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/CarcasModelBuilder.cpp.o
.PHONY : src/builder/CarcasModelBuilder.cpp.o

src/builder/CarcasModelBuilder.i: src/builder/CarcasModelBuilder.cpp.i
.PHONY : src/builder/CarcasModelBuilder.i

# target to preprocess a source file
src/builder/CarcasModelBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/CarcasModelBuilder.cpp.i
.PHONY : src/builder/CarcasModelBuilder.cpp.i

src/builder/CarcasModelBuilder.s: src/builder/CarcasModelBuilder.cpp.s
.PHONY : src/builder/CarcasModelBuilder.s

# target to generate assembly for a file
src/builder/CarcasModelBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/CarcasModelBuilder.cpp.s
.PHONY : src/builder/CarcasModelBuilder.cpp.s

src/builder/SceneBuilder.o: src/builder/SceneBuilder.cpp.o
.PHONY : src/builder/SceneBuilder.o

# target to build an object file
src/builder/SceneBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/SceneBuilder.cpp.o
.PHONY : src/builder/SceneBuilder.cpp.o

src/builder/SceneBuilder.i: src/builder/SceneBuilder.cpp.i
.PHONY : src/builder/SceneBuilder.i

# target to preprocess a source file
src/builder/SceneBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/SceneBuilder.cpp.i
.PHONY : src/builder/SceneBuilder.cpp.i

src/builder/SceneBuilder.s: src/builder/SceneBuilder.cpp.s
.PHONY : src/builder/SceneBuilder.s

# target to generate assembly for a file
src/builder/SceneBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/builder/SceneBuilder.cpp.s
.PHONY : src/builder/SceneBuilder.cpp.s

src/command/CameraCommands.o: src/command/CameraCommands.cpp.o
.PHONY : src/command/CameraCommands.o

# target to build an object file
src/command/CameraCommands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/CameraCommands.cpp.o
.PHONY : src/command/CameraCommands.cpp.o

src/command/CameraCommands.i: src/command/CameraCommands.cpp.i
.PHONY : src/command/CameraCommands.i

# target to preprocess a source file
src/command/CameraCommands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/CameraCommands.cpp.i
.PHONY : src/command/CameraCommands.cpp.i

src/command/CameraCommands.s: src/command/CameraCommands.cpp.s
.PHONY : src/command/CameraCommands.s

# target to generate assembly for a file
src/command/CameraCommands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/CameraCommands.cpp.s
.PHONY : src/command/CameraCommands.cpp.s

src/command/HistoryCommands.o: src/command/HistoryCommands.cpp.o
.PHONY : src/command/HistoryCommands.o

# target to build an object file
src/command/HistoryCommands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/HistoryCommands.cpp.o
.PHONY : src/command/HistoryCommands.cpp.o

src/command/HistoryCommands.i: src/command/HistoryCommands.cpp.i
.PHONY : src/command/HistoryCommands.i

# target to preprocess a source file
src/command/HistoryCommands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/HistoryCommands.cpp.i
.PHONY : src/command/HistoryCommands.cpp.i

src/command/HistoryCommands.s: src/command/HistoryCommands.cpp.s
.PHONY : src/command/HistoryCommands.s

# target to generate assembly for a file
src/command/HistoryCommands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/HistoryCommands.cpp.s
.PHONY : src/command/HistoryCommands.cpp.s

src/command/ModelCommands.o: src/command/ModelCommands.cpp.o
.PHONY : src/command/ModelCommands.o

# target to build an object file
src/command/ModelCommands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/ModelCommands.cpp.o
.PHONY : src/command/ModelCommands.cpp.o

src/command/ModelCommands.i: src/command/ModelCommands.cpp.i
.PHONY : src/command/ModelCommands.i

# target to preprocess a source file
src/command/ModelCommands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/ModelCommands.cpp.i
.PHONY : src/command/ModelCommands.cpp.i

src/command/ModelCommands.s: src/command/ModelCommands.cpp.s
.PHONY : src/command/ModelCommands.s

# target to generate assembly for a file
src/command/ModelCommands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/ModelCommands.cpp.s
.PHONY : src/command/ModelCommands.cpp.s

src/command/SceneCommands.o: src/command/SceneCommands.cpp.o
.PHONY : src/command/SceneCommands.o

# target to build an object file
src/command/SceneCommands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/SceneCommands.cpp.o
.PHONY : src/command/SceneCommands.cpp.o

src/command/SceneCommands.i: src/command/SceneCommands.cpp.i
.PHONY : src/command/SceneCommands.i

# target to preprocess a source file
src/command/SceneCommands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/SceneCommands.cpp.i
.PHONY : src/command/SceneCommands.cpp.i

src/command/SceneCommands.s: src/command/SceneCommands.cpp.s
.PHONY : src/command/SceneCommands.s

# target to generate assembly for a file
src/command/SceneCommands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/SceneCommands.cpp.s
.PHONY : src/command/SceneCommands.cpp.s

src/command/SetMaterialCommand.o: src/command/SetMaterialCommand.cpp.o
.PHONY : src/command/SetMaterialCommand.o

# target to build an object file
src/command/SetMaterialCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/SetMaterialCommand.cpp.o
.PHONY : src/command/SetMaterialCommand.cpp.o

src/command/SetMaterialCommand.i: src/command/SetMaterialCommand.cpp.i
.PHONY : src/command/SetMaterialCommand.i

# target to preprocess a source file
src/command/SetMaterialCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/SetMaterialCommand.cpp.i
.PHONY : src/command/SetMaterialCommand.cpp.i

src/command/SetMaterialCommand.s: src/command/SetMaterialCommand.cpp.s
.PHONY : src/command/SetMaterialCommand.s

# target to generate assembly for a file
src/command/SetMaterialCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/SetMaterialCommand.cpp.s
.PHONY : src/command/SetMaterialCommand.cpp.s

src/command/TransformCommands.o: src/command/TransformCommands.cpp.o
.PHONY : src/command/TransformCommands.o

# target to build an object file
src/command/TransformCommands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/TransformCommands.cpp.o
.PHONY : src/command/TransformCommands.cpp.o

src/command/TransformCommands.i: src/command/TransformCommands.cpp.i
.PHONY : src/command/TransformCommands.i

# target to preprocess a source file
src/command/TransformCommands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/TransformCommands.cpp.i
.PHONY : src/command/TransformCommands.cpp.i

src/command/TransformCommands.s: src/command/TransformCommands.cpp.s
.PHONY : src/command/TransformCommands.s

# target to generate assembly for a file
src/command/TransformCommands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/command/TransformCommands.cpp.s
.PHONY : src/command/TransformCommands.cpp.s

src/composite/BaseObject.o: src/composite/BaseObject.cpp.o
.PHONY : src/composite/BaseObject.o

# target to build an object file
src/composite/BaseObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/BaseObject.cpp.o
.PHONY : src/composite/BaseObject.cpp.o

src/composite/BaseObject.i: src/composite/BaseObject.cpp.i
.PHONY : src/composite/BaseObject.i

# target to preprocess a source file
src/composite/BaseObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/BaseObject.cpp.i
.PHONY : src/composite/BaseObject.cpp.i

src/composite/BaseObject.s: src/composite/BaseObject.cpp.s
.PHONY : src/composite/BaseObject.s

# target to generate assembly for a file
src/composite/BaseObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/BaseObject.cpp.s
.PHONY : src/composite/BaseObject.cpp.s

src/composite/Camera.o: src/composite/Camera.cpp.o
.PHONY : src/composite/Camera.o

# target to build an object file
src/composite/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Camera.cpp.o
.PHONY : src/composite/Camera.cpp.o

src/composite/Camera.i: src/composite/Camera.cpp.i
.PHONY : src/composite/Camera.i

# target to preprocess a source file
src/composite/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Camera.cpp.i
.PHONY : src/composite/Camera.cpp.i

src/composite/Camera.s: src/composite/Camera.cpp.s
.PHONY : src/composite/Camera.s

# target to generate assembly for a file
src/composite/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Camera.cpp.s
.PHONY : src/composite/Camera.cpp.s

src/composite/CompositeObject.o: src/composite/CompositeObject.cpp.o
.PHONY : src/composite/CompositeObject.o

# target to build an object file
src/composite/CompositeObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/CompositeObject.cpp.o
.PHONY : src/composite/CompositeObject.cpp.o

src/composite/CompositeObject.i: src/composite/CompositeObject.cpp.i
.PHONY : src/composite/CompositeObject.i

# target to preprocess a source file
src/composite/CompositeObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/CompositeObject.cpp.i
.PHONY : src/composite/CompositeObject.cpp.i

src/composite/CompositeObject.s: src/composite/CompositeObject.cpp.s
.PHONY : src/composite/CompositeObject.s

# target to generate assembly for a file
src/composite/CompositeObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/CompositeObject.cpp.s
.PHONY : src/composite/CompositeObject.cpp.s

src/composite/Light.o: src/composite/Light.cpp.o
.PHONY : src/composite/Light.o

# target to build an object file
src/composite/Light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Light.cpp.o
.PHONY : src/composite/Light.cpp.o

src/composite/Light.i: src/composite/Light.cpp.i
.PHONY : src/composite/Light.i

# target to preprocess a source file
src/composite/Light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Light.cpp.i
.PHONY : src/composite/Light.cpp.i

src/composite/Light.s: src/composite/Light.cpp.s
.PHONY : src/composite/Light.s

# target to generate assembly for a file
src/composite/Light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Light.cpp.s
.PHONY : src/composite/Light.cpp.s

src/composite/Model.o: src/composite/Model.cpp.o
.PHONY : src/composite/Model.o

# target to build an object file
src/composite/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Model.cpp.o
.PHONY : src/composite/Model.cpp.o

src/composite/Model.i: src/composite/Model.cpp.i
.PHONY : src/composite/Model.i

# target to preprocess a source file
src/composite/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Model.cpp.i
.PHONY : src/composite/Model.cpp.i

src/composite/Model.s: src/composite/Model.cpp.s
.PHONY : src/composite/Model.s

# target to generate assembly for a file
src/composite/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Model.cpp.s
.PHONY : src/composite/Model.cpp.s

src/composite/Scene.o: src/composite/Scene.cpp.o
.PHONY : src/composite/Scene.o

# target to build an object file
src/composite/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Scene.cpp.o
.PHONY : src/composite/Scene.cpp.o

src/composite/Scene.i: src/composite/Scene.cpp.i
.PHONY : src/composite/Scene.i

# target to preprocess a source file
src/composite/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Scene.cpp.i
.PHONY : src/composite/Scene.cpp.i

src/composite/Scene.s: src/composite/Scene.cpp.s
.PHONY : src/composite/Scene.s

# target to generate assembly for a file
src/composite/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/composite/Scene.cpp.s
.PHONY : src/composite/Scene.cpp.s

src/data/MaterialPresets.o: src/data/MaterialPresets.cpp.o
.PHONY : src/data/MaterialPresets.o

# target to build an object file
src/data/MaterialPresets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/data/MaterialPresets.cpp.o
.PHONY : src/data/MaterialPresets.cpp.o

src/data/MaterialPresets.i: src/data/MaterialPresets.cpp.i
.PHONY : src/data/MaterialPresets.i

# target to preprocess a source file
src/data/MaterialPresets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/data/MaterialPresets.cpp.i
.PHONY : src/data/MaterialPresets.cpp.i

src/data/MaterialPresets.s: src/data/MaterialPresets.cpp.s
.PHONY : src/data/MaterialPresets.s

# target to generate assembly for a file
src/data/MaterialPresets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/data/MaterialPresets.cpp.s
.PHONY : src/data/MaterialPresets.cpp.s

src/data/Point.o: src/data/Point.cpp.o
.PHONY : src/data/Point.o

# target to build an object file
src/data/Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/data/Point.cpp.o
.PHONY : src/data/Point.cpp.o

src/data/Point.i: src/data/Point.cpp.i
.PHONY : src/data/Point.i

# target to preprocess a source file
src/data/Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/data/Point.cpp.i
.PHONY : src/data/Point.cpp.i

src/data/Point.s: src/data/Point.cpp.s
.PHONY : src/data/Point.s

# target to generate assembly for a file
src/data/Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/data/Point.cpp.s
.PHONY : src/data/Point.cpp.s

src/director/AssimpDirector.o: src/director/AssimpDirector.cpp.o
.PHONY : src/director/AssimpDirector.o

# target to build an object file
src/director/AssimpDirector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/AssimpDirector.cpp.o
.PHONY : src/director/AssimpDirector.cpp.o

src/director/AssimpDirector.i: src/director/AssimpDirector.cpp.i
.PHONY : src/director/AssimpDirector.i

# target to preprocess a source file
src/director/AssimpDirector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/AssimpDirector.cpp.i
.PHONY : src/director/AssimpDirector.cpp.i

src/director/AssimpDirector.s: src/director/AssimpDirector.cpp.s
.PHONY : src/director/AssimpDirector.s

# target to generate assembly for a file
src/director/AssimpDirector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/AssimpDirector.cpp.s
.PHONY : src/director/AssimpDirector.cpp.s

src/director/CarcasCameraDirector.o: src/director/CarcasCameraDirector.cpp.o
.PHONY : src/director/CarcasCameraDirector.o

# target to build an object file
src/director/CarcasCameraDirector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/CarcasCameraDirector.cpp.o
.PHONY : src/director/CarcasCameraDirector.cpp.o

src/director/CarcasCameraDirector.i: src/director/CarcasCameraDirector.cpp.i
.PHONY : src/director/CarcasCameraDirector.i

# target to preprocess a source file
src/director/CarcasCameraDirector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/CarcasCameraDirector.cpp.i
.PHONY : src/director/CarcasCameraDirector.cpp.i

src/director/CarcasCameraDirector.s: src/director/CarcasCameraDirector.cpp.s
.PHONY : src/director/CarcasCameraDirector.s

# target to generate assembly for a file
src/director/CarcasCameraDirector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/CarcasCameraDirector.cpp.s
.PHONY : src/director/CarcasCameraDirector.cpp.s

src/director/CarcasModelDirector.o: src/director/CarcasModelDirector.cpp.o
.PHONY : src/director/CarcasModelDirector.o

# target to build an object file
src/director/CarcasModelDirector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/CarcasModelDirector.cpp.o
.PHONY : src/director/CarcasModelDirector.cpp.o

src/director/CarcasModelDirector.i: src/director/CarcasModelDirector.cpp.i
.PHONY : src/director/CarcasModelDirector.i

# target to preprocess a source file
src/director/CarcasModelDirector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/CarcasModelDirector.cpp.i
.PHONY : src/director/CarcasModelDirector.cpp.i

src/director/CarcasModelDirector.s: src/director/CarcasModelDirector.cpp.s
.PHONY : src/director/CarcasModelDirector.s

# target to generate assembly for a file
src/director/CarcasModelDirector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/CarcasModelDirector.cpp.s
.PHONY : src/director/CarcasModelDirector.cpp.s

src/director/SceneDirector.o: src/director/SceneDirector.cpp.o
.PHONY : src/director/SceneDirector.o

# target to build an object file
src/director/SceneDirector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/SceneDirector.cpp.o
.PHONY : src/director/SceneDirector.cpp.o

src/director/SceneDirector.i: src/director/SceneDirector.cpp.i
.PHONY : src/director/SceneDirector.i

# target to preprocess a source file
src/director/SceneDirector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/SceneDirector.cpp.i
.PHONY : src/director/SceneDirector.cpp.i

src/director/SceneDirector.s: src/director/SceneDirector.cpp.s
.PHONY : src/director/SceneDirector.s

# target to generate assembly for a file
src/director/SceneDirector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/director/SceneDirector.cpp.s
.PHONY : src/director/SceneDirector.cpp.s

src/facade/Facade.o: src/facade/Facade.cpp.o
.PHONY : src/facade/Facade.o

# target to build an object file
src/facade/Facade.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/facade/Facade.cpp.o
.PHONY : src/facade/Facade.cpp.o

src/facade/Facade.i: src/facade/Facade.cpp.i
.PHONY : src/facade/Facade.i

# target to preprocess a source file
src/facade/Facade.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/facade/Facade.cpp.i
.PHONY : src/facade/Facade.cpp.i

src/facade/Facade.s: src/facade/Facade.cpp.s
.PHONY : src/facade/Facade.s

# target to generate assembly for a file
src/facade/Facade.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/facade/Facade.cpp.s
.PHONY : src/facade/Facade.cpp.s

src/factory/QtDrawer.o: src/factory/QtDrawer.cpp.o
.PHONY : src/factory/QtDrawer.o

# target to build an object file
src/factory/QtDrawer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/factory/QtDrawer.cpp.o
.PHONY : src/factory/QtDrawer.cpp.o

src/factory/QtDrawer.i: src/factory/QtDrawer.cpp.i
.PHONY : src/factory/QtDrawer.i

# target to preprocess a source file
src/factory/QtDrawer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/factory/QtDrawer.cpp.i
.PHONY : src/factory/QtDrawer.cpp.i

src/factory/QtDrawer.s: src/factory/QtDrawer.cpp.s
.PHONY : src/factory/QtDrawer.s

# target to generate assembly for a file
src/factory/QtDrawer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/factory/QtDrawer.cpp.s
.PHONY : src/factory/QtDrawer.cpp.s

src/factory/QtDrawerFactory.o: src/factory/QtDrawerFactory.cpp.o
.PHONY : src/factory/QtDrawerFactory.o

# target to build an object file
src/factory/QtDrawerFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/factory/QtDrawerFactory.cpp.o
.PHONY : src/factory/QtDrawerFactory.cpp.o

src/factory/QtDrawerFactory.i: src/factory/QtDrawerFactory.cpp.i
.PHONY : src/factory/QtDrawerFactory.i

# target to preprocess a source file
src/factory/QtDrawerFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/factory/QtDrawerFactory.cpp.i
.PHONY : src/factory/QtDrawerFactory.cpp.i

src/factory/QtDrawerFactory.s: src/factory/QtDrawerFactory.cpp.s
.PHONY : src/factory/QtDrawerFactory.s

# target to generate assembly for a file
src/factory/QtDrawerFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/factory/QtDrawerFactory.cpp.s
.PHONY : src/factory/QtDrawerFactory.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/manager/DrawManager.o: src/manager/DrawManager.cpp.o
.PHONY : src/manager/DrawManager.o

# target to build an object file
src/manager/DrawManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/DrawManager.cpp.o
.PHONY : src/manager/DrawManager.cpp.o

src/manager/DrawManager.i: src/manager/DrawManager.cpp.i
.PHONY : src/manager/DrawManager.i

# target to preprocess a source file
src/manager/DrawManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/DrawManager.cpp.i
.PHONY : src/manager/DrawManager.cpp.i

src/manager/DrawManager.s: src/manager/DrawManager.cpp.s
.PHONY : src/manager/DrawManager.s

# target to generate assembly for a file
src/manager/DrawManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/DrawManager.cpp.s
.PHONY : src/manager/DrawManager.cpp.s

src/manager/HistoryManager.o: src/manager/HistoryManager.cpp.o
.PHONY : src/manager/HistoryManager.o

# target to build an object file
src/manager/HistoryManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/HistoryManager.cpp.o
.PHONY : src/manager/HistoryManager.cpp.o

src/manager/HistoryManager.i: src/manager/HistoryManager.cpp.i
.PHONY : src/manager/HistoryManager.i

# target to preprocess a source file
src/manager/HistoryManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/HistoryManager.cpp.i
.PHONY : src/manager/HistoryManager.cpp.i

src/manager/HistoryManager.s: src/manager/HistoryManager.cpp.s
.PHONY : src/manager/HistoryManager.s

# target to generate assembly for a file
src/manager/HistoryManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/HistoryManager.cpp.s
.PHONY : src/manager/HistoryManager.cpp.s

src/manager/LoadManager.o: src/manager/LoadManager.cpp.o
.PHONY : src/manager/LoadManager.o

# target to build an object file
src/manager/LoadManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/LoadManager.cpp.o
.PHONY : src/manager/LoadManager.cpp.o

src/manager/LoadManager.i: src/manager/LoadManager.cpp.i
.PHONY : src/manager/LoadManager.i

# target to preprocess a source file
src/manager/LoadManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/LoadManager.cpp.i
.PHONY : src/manager/LoadManager.cpp.i

src/manager/LoadManager.s: src/manager/LoadManager.cpp.s
.PHONY : src/manager/LoadManager.s

# target to generate assembly for a file
src/manager/LoadManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/LoadManager.cpp.s
.PHONY : src/manager/LoadManager.cpp.s

src/manager/SceneManager.o: src/manager/SceneManager.cpp.o
.PHONY : src/manager/SceneManager.o

# target to build an object file
src/manager/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/SceneManager.cpp.o
.PHONY : src/manager/SceneManager.cpp.o

src/manager/SceneManager.i: src/manager/SceneManager.cpp.i
.PHONY : src/manager/SceneManager.i

# target to preprocess a source file
src/manager/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/SceneManager.cpp.i
.PHONY : src/manager/SceneManager.cpp.i

src/manager/SceneManager.s: src/manager/SceneManager.cpp.s
.PHONY : src/manager/SceneManager.s

# target to generate assembly for a file
src/manager/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/SceneManager.cpp.s
.PHONY : src/manager/SceneManager.cpp.s

src/manager/TransformManager.o: src/manager/TransformManager.cpp.o
.PHONY : src/manager/TransformManager.o

# target to build an object file
src/manager/TransformManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/TransformManager.cpp.o
.PHONY : src/manager/TransformManager.cpp.o

src/manager/TransformManager.i: src/manager/TransformManager.cpp.i
.PHONY : src/manager/TransformManager.i

# target to preprocess a source file
src/manager/TransformManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/TransformManager.cpp.i
.PHONY : src/manager/TransformManager.cpp.i

src/manager/TransformManager.s: src/manager/TransformManager.cpp.s
.PHONY : src/manager/TransformManager.s

# target to generate assembly for a file
src/manager/TransformManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/manager/TransformManager.cpp.s
.PHONY : src/manager/TransformManager.cpp.s

src/memento/Memento.o: src/memento/Memento.cpp.o
.PHONY : src/memento/Memento.o

# target to build an object file
src/memento/Memento.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/memento/Memento.cpp.o
.PHONY : src/memento/Memento.cpp.o

src/memento/Memento.i: src/memento/Memento.cpp.i
.PHONY : src/memento/Memento.i

# target to preprocess a source file
src/memento/Memento.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/memento/Memento.cpp.i
.PHONY : src/memento/Memento.cpp.i

src/memento/Memento.s: src/memento/Memento.cpp.s
.PHONY : src/memento/Memento.s

# target to generate assembly for a file
src/memento/Memento.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/memento/Memento.cpp.s
.PHONY : src/memento/Memento.cpp.s

src/reader/AssimpReader.o: src/reader/AssimpReader.cpp.o
.PHONY : src/reader/AssimpReader.o

# target to build an object file
src/reader/AssimpReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/AssimpReader.cpp.o
.PHONY : src/reader/AssimpReader.cpp.o

src/reader/AssimpReader.i: src/reader/AssimpReader.cpp.i
.PHONY : src/reader/AssimpReader.i

# target to preprocess a source file
src/reader/AssimpReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/AssimpReader.cpp.i
.PHONY : src/reader/AssimpReader.cpp.i

src/reader/AssimpReader.s: src/reader/AssimpReader.cpp.s
.PHONY : src/reader/AssimpReader.s

# target to generate assembly for a file
src/reader/AssimpReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/AssimpReader.cpp.s
.PHONY : src/reader/AssimpReader.cpp.s

src/reader/AutoReader.o: src/reader/AutoReader.cpp.o
.PHONY : src/reader/AutoReader.o

# target to build an object file
src/reader/AutoReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/AutoReader.cpp.o
.PHONY : src/reader/AutoReader.cpp.o

src/reader/AutoReader.i: src/reader/AutoReader.cpp.i
.PHONY : src/reader/AutoReader.i

# target to preprocess a source file
src/reader/AutoReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/AutoReader.cpp.i
.PHONY : src/reader/AutoReader.cpp.i

src/reader/AutoReader.s: src/reader/AutoReader.cpp.s
.PHONY : src/reader/AutoReader.s

# target to generate assembly for a file
src/reader/AutoReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/AutoReader.cpp.s
.PHONY : src/reader/AutoReader.cpp.s

src/reader/BinaryReader.o: src/reader/BinaryReader.cpp.o
.PHONY : src/reader/BinaryReader.o

# target to build an object file
src/reader/BinaryReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/BinaryReader.cpp.o
.PHONY : src/reader/BinaryReader.cpp.o

src/reader/BinaryReader.i: src/reader/BinaryReader.cpp.i
.PHONY : src/reader/BinaryReader.i

# target to preprocess a source file
src/reader/BinaryReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/BinaryReader.cpp.i
.PHONY : src/reader/BinaryReader.cpp.i

src/reader/BinaryReader.s: src/reader/BinaryReader.cpp.s
.PHONY : src/reader/BinaryReader.s

# target to generate assembly for a file
src/reader/BinaryReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/BinaryReader.cpp.s
.PHONY : src/reader/BinaryReader.cpp.s

src/reader/FileReader.o: src/reader/FileReader.cpp.o
.PHONY : src/reader/FileReader.o

# target to build an object file
src/reader/FileReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/FileReader.cpp.o
.PHONY : src/reader/FileReader.cpp.o

src/reader/FileReader.i: src/reader/FileReader.cpp.i
.PHONY : src/reader/FileReader.i

# target to preprocess a source file
src/reader/FileReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/FileReader.cpp.i
.PHONY : src/reader/FileReader.cpp.i

src/reader/FileReader.s: src/reader/FileReader.cpp.s
.PHONY : src/reader/FileReader.s

# target to generate assembly for a file
src/reader/FileReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/reader/FileReader.cpp.s
.PHONY : src/reader/FileReader.cpp.s

src/solution/Solution.o: src/solution/Solution.cpp.o
.PHONY : src/solution/Solution.o

# target to build an object file
src/solution/Solution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/solution/Solution.cpp.o
.PHONY : src/solution/Solution.cpp.o

src/solution/Solution.i: src/solution/Solution.cpp.i
.PHONY : src/solution/Solution.i

# target to preprocess a source file
src/solution/Solution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/solution/Solution.cpp.i
.PHONY : src/solution/Solution.cpp.i

src/solution/Solution.s: src/solution/Solution.cpp.s
.PHONY : src/solution/Solution.s

# target to generate assembly for a file
src/solution/Solution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/solution/Solution.cpp.s
.PHONY : src/solution/Solution.cpp.s

src/ui/MainWindow.o: src/ui/MainWindow.cpp.o
.PHONY : src/ui/MainWindow.o

# target to build an object file
src/ui/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/ui/MainWindow.cpp.o
.PHONY : src/ui/MainWindow.cpp.o

src/ui/MainWindow.i: src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.i

# target to preprocess a source file
src/ui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.cpp.i

src/ui/MainWindow.s: src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.s

# target to generate assembly for a file
src/ui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.cpp.s

src/visitor/DrawVisitor.o: src/visitor/DrawVisitor.cpp.o
.PHONY : src/visitor/DrawVisitor.o

# target to build an object file
src/visitor/DrawVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/DrawVisitor.cpp.o
.PHONY : src/visitor/DrawVisitor.cpp.o

src/visitor/DrawVisitor.i: src/visitor/DrawVisitor.cpp.i
.PHONY : src/visitor/DrawVisitor.i

# target to preprocess a source file
src/visitor/DrawVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/DrawVisitor.cpp.i
.PHONY : src/visitor/DrawVisitor.cpp.i

src/visitor/DrawVisitor.s: src/visitor/DrawVisitor.cpp.s
.PHONY : src/visitor/DrawVisitor.s

# target to generate assembly for a file
src/visitor/DrawVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/DrawVisitor.cpp.s
.PHONY : src/visitor/DrawVisitor.cpp.s

src/visitor/MoveVisitor.o: src/visitor/MoveVisitor.cpp.o
.PHONY : src/visitor/MoveVisitor.o

# target to build an object file
src/visitor/MoveVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/MoveVisitor.cpp.o
.PHONY : src/visitor/MoveVisitor.cpp.o

src/visitor/MoveVisitor.i: src/visitor/MoveVisitor.cpp.i
.PHONY : src/visitor/MoveVisitor.i

# target to preprocess a source file
src/visitor/MoveVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/MoveVisitor.cpp.i
.PHONY : src/visitor/MoveVisitor.cpp.i

src/visitor/MoveVisitor.s: src/visitor/MoveVisitor.cpp.s
.PHONY : src/visitor/MoveVisitor.s

# target to generate assembly for a file
src/visitor/MoveVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/MoveVisitor.cpp.s
.PHONY : src/visitor/MoveVisitor.cpp.s

src/visitor/RotateVisitor.o: src/visitor/RotateVisitor.cpp.o
.PHONY : src/visitor/RotateVisitor.o

# target to build an object file
src/visitor/RotateVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/RotateVisitor.cpp.o
.PHONY : src/visitor/RotateVisitor.cpp.o

src/visitor/RotateVisitor.i: src/visitor/RotateVisitor.cpp.i
.PHONY : src/visitor/RotateVisitor.i

# target to preprocess a source file
src/visitor/RotateVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/RotateVisitor.cpp.i
.PHONY : src/visitor/RotateVisitor.cpp.i

src/visitor/RotateVisitor.s: src/visitor/RotateVisitor.cpp.s
.PHONY : src/visitor/RotateVisitor.s

# target to generate assembly for a file
src/visitor/RotateVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/RotateVisitor.cpp.s
.PHONY : src/visitor/RotateVisitor.cpp.s

src/visitor/ScaleVisitor.o: src/visitor/ScaleVisitor.cpp.o
.PHONY : src/visitor/ScaleVisitor.o

# target to build an object file
src/visitor/ScaleVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/ScaleVisitor.cpp.o
.PHONY : src/visitor/ScaleVisitor.cpp.o

src/visitor/ScaleVisitor.i: src/visitor/ScaleVisitor.cpp.i
.PHONY : src/visitor/ScaleVisitor.i

# target to preprocess a source file
src/visitor/ScaleVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/ScaleVisitor.cpp.i
.PHONY : src/visitor/ScaleVisitor.cpp.i

src/visitor/ScaleVisitor.s: src/visitor/ScaleVisitor.cpp.s
.PHONY : src/visitor/ScaleVisitor.s

# target to generate assembly for a file
src/visitor/ScaleVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_Lab3_FrameViewer.dir/build.make CMakeFiles/OOP_Lab3_FrameViewer.dir/src/visitor/ScaleVisitor.cpp.s
.PHONY : src/visitor/ScaleVisitor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OOP_Lab3_FrameViewer_autogen"
	@echo "... OOP_Lab3_FrameViewer_autogen_timestamp_deps"
	@echo "... OOP_Lab3_FrameViewer"
	@echo "... OOP_Lab3_FrameViewer_autogen/mocs_compilation.o"
	@echo "... OOP_Lab3_FrameViewer_autogen/mocs_compilation.i"
	@echo "... OOP_Lab3_FrameViewer_autogen/mocs_compilation.s"
	@echo "... src/bridge/AssimpModelImpl.o"
	@echo "... src/bridge/AssimpModelImpl.i"
	@echo "... src/bridge/AssimpModelImpl.s"
	@echo "... src/bridge/CarcasCamera.o"
	@echo "... src/bridge/CarcasCamera.i"
	@echo "... src/bridge/CarcasCamera.s"
	@echo "... src/bridge/LightImpl.o"
	@echo "... src/bridge/LightImpl.i"
	@echo "... src/bridge/LightImpl.s"
	@echo "... src/bridge/VectorCompositeImpl.o"
	@echo "... src/bridge/VectorCompositeImpl.i"
	@echo "... src/bridge/VectorCompositeImpl.s"
	@echo "... src/builder/AssimpModelBuilder.o"
	@echo "... src/builder/AssimpModelBuilder.i"
	@echo "... src/builder/AssimpModelBuilder.s"
	@echo "... src/builder/BaseBuilder.o"
	@echo "... src/builder/BaseBuilder.i"
	@echo "... src/builder/BaseBuilder.s"
	@echo "... src/builder/CarcasCameraBuilder.o"
	@echo "... src/builder/CarcasCameraBuilder.i"
	@echo "... src/builder/CarcasCameraBuilder.s"
	@echo "... src/builder/CarcasModelBuilder.o"
	@echo "... src/builder/CarcasModelBuilder.i"
	@echo "... src/builder/CarcasModelBuilder.s"
	@echo "... src/builder/SceneBuilder.o"
	@echo "... src/builder/SceneBuilder.i"
	@echo "... src/builder/SceneBuilder.s"
	@echo "... src/command/CameraCommands.o"
	@echo "... src/command/CameraCommands.i"
	@echo "... src/command/CameraCommands.s"
	@echo "... src/command/HistoryCommands.o"
	@echo "... src/command/HistoryCommands.i"
	@echo "... src/command/HistoryCommands.s"
	@echo "... src/command/ModelCommands.o"
	@echo "... src/command/ModelCommands.i"
	@echo "... src/command/ModelCommands.s"
	@echo "... src/command/SceneCommands.o"
	@echo "... src/command/SceneCommands.i"
	@echo "... src/command/SceneCommands.s"
	@echo "... src/command/SetMaterialCommand.o"
	@echo "... src/command/SetMaterialCommand.i"
	@echo "... src/command/SetMaterialCommand.s"
	@echo "... src/command/TransformCommands.o"
	@echo "... src/command/TransformCommands.i"
	@echo "... src/command/TransformCommands.s"
	@echo "... src/composite/BaseObject.o"
	@echo "... src/composite/BaseObject.i"
	@echo "... src/composite/BaseObject.s"
	@echo "... src/composite/Camera.o"
	@echo "... src/composite/Camera.i"
	@echo "... src/composite/Camera.s"
	@echo "... src/composite/CompositeObject.o"
	@echo "... src/composite/CompositeObject.i"
	@echo "... src/composite/CompositeObject.s"
	@echo "... src/composite/Light.o"
	@echo "... src/composite/Light.i"
	@echo "... src/composite/Light.s"
	@echo "... src/composite/Model.o"
	@echo "... src/composite/Model.i"
	@echo "... src/composite/Model.s"
	@echo "... src/composite/Scene.o"
	@echo "... src/composite/Scene.i"
	@echo "... src/composite/Scene.s"
	@echo "... src/data/MaterialPresets.o"
	@echo "... src/data/MaterialPresets.i"
	@echo "... src/data/MaterialPresets.s"
	@echo "... src/data/Point.o"
	@echo "... src/data/Point.i"
	@echo "... src/data/Point.s"
	@echo "... src/director/AssimpDirector.o"
	@echo "... src/director/AssimpDirector.i"
	@echo "... src/director/AssimpDirector.s"
	@echo "... src/director/CarcasCameraDirector.o"
	@echo "... src/director/CarcasCameraDirector.i"
	@echo "... src/director/CarcasCameraDirector.s"
	@echo "... src/director/CarcasModelDirector.o"
	@echo "... src/director/CarcasModelDirector.i"
	@echo "... src/director/CarcasModelDirector.s"
	@echo "... src/director/SceneDirector.o"
	@echo "... src/director/SceneDirector.i"
	@echo "... src/director/SceneDirector.s"
	@echo "... src/facade/Facade.o"
	@echo "... src/facade/Facade.i"
	@echo "... src/facade/Facade.s"
	@echo "... src/factory/QtDrawer.o"
	@echo "... src/factory/QtDrawer.i"
	@echo "... src/factory/QtDrawer.s"
	@echo "... src/factory/QtDrawerFactory.o"
	@echo "... src/factory/QtDrawerFactory.i"
	@echo "... src/factory/QtDrawerFactory.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/manager/DrawManager.o"
	@echo "... src/manager/DrawManager.i"
	@echo "... src/manager/DrawManager.s"
	@echo "... src/manager/HistoryManager.o"
	@echo "... src/manager/HistoryManager.i"
	@echo "... src/manager/HistoryManager.s"
	@echo "... src/manager/LoadManager.o"
	@echo "... src/manager/LoadManager.i"
	@echo "... src/manager/LoadManager.s"
	@echo "... src/manager/SceneManager.o"
	@echo "... src/manager/SceneManager.i"
	@echo "... src/manager/SceneManager.s"
	@echo "... src/manager/TransformManager.o"
	@echo "... src/manager/TransformManager.i"
	@echo "... src/manager/TransformManager.s"
	@echo "... src/memento/Memento.o"
	@echo "... src/memento/Memento.i"
	@echo "... src/memento/Memento.s"
	@echo "... src/reader/AssimpReader.o"
	@echo "... src/reader/AssimpReader.i"
	@echo "... src/reader/AssimpReader.s"
	@echo "... src/reader/AutoReader.o"
	@echo "... src/reader/AutoReader.i"
	@echo "... src/reader/AutoReader.s"
	@echo "... src/reader/BinaryReader.o"
	@echo "... src/reader/BinaryReader.i"
	@echo "... src/reader/BinaryReader.s"
	@echo "... src/reader/FileReader.o"
	@echo "... src/reader/FileReader.i"
	@echo "... src/reader/FileReader.s"
	@echo "... src/solution/Solution.o"
	@echo "... src/solution/Solution.i"
	@echo "... src/solution/Solution.s"
	@echo "... src/ui/MainWindow.o"
	@echo "... src/ui/MainWindow.i"
	@echo "... src/ui/MainWindow.s"
	@echo "... src/visitor/DrawVisitor.o"
	@echo "... src/visitor/DrawVisitor.i"
	@echo "... src/visitor/DrawVisitor.s"
	@echo "... src/visitor/MoveVisitor.o"
	@echo "... src/visitor/MoveVisitor.i"
	@echo "... src/visitor/MoveVisitor.s"
	@echo "... src/visitor/RotateVisitor.o"
	@echo "... src/visitor/RotateVisitor.i"
	@echo "... src/visitor/RotateVisitor.s"
	@echo "... src/visitor/ScaleVisitor.o"
	@echo "... src/visitor/ScaleVisitor.i"
	@echo "... src/visitor/ScaleVisitor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

